### ISSUE TITLE
Besu sync problems

### ISSUE THREAD

**Issue by holiman** [hyperledger/besu#797]
This is a sync - test: https://hivetests.ethdevops.io/?suite=1587974674-63bde328c122e5fc52af6b280106531c.json 
The sync server tries to import 10 blocks, and the tests then proceed trying to sync other clients from that source. 

## Source
Here's the log from when Besu is the sync source: https://hivetests.ethdevops.io/viewer.html?file=results/besu_latest/client-bb212852.log#L29

And here, the log shows that Besu _did_ exit properly after the import, and we started a second run with it in normal mode: 
https://hivetests.ethdevops.io/viewer.html?file=results/besu_latest/client-bb212852.log#L34

Source boot: `starting main client: /opt/besu/bin/besu  --network-id=1 --sync-mode=FAST --logging=INFO --genesis-file=/besugenesis.json --graphql-http-enabled --graphql-http-host=0.0.0.0 --host-whitelist=* --rpc-http-enabled --rpc-http-api=ETH,NET,WEB3,ADMIN --rpc-http-host=0.0.0.0`

It reports
```
2020-04-27 07:55:41.613+00:00 | main | INFO  | DefaultP2PNetwork | Enode URL enode://26b2749070b72d21bdffad1ad3710efb146874491862b0bddc571b4532609fb49f718cae05b550e79b15f2a75f1900432fe0439c7af7bcdac8b937434c7ffe8d@127.0.0.1:30303
```

## Sink

Another besu instance is here: https://hivetests.ethdevops.io/viewer.html?file=results/besu_latest/client-e4c71400.log . Hive tries to peer that one with the first one, and expects them to sync up. 

Sink boot: ` /opt/besu/bin/besu  --bootnodes=enode://26b2749070b72d21bdffad1ad3710efb146874491862b0bddc571b4532609fb49f718cae05b550e79b15f2a75f1900432fe0439c7af7bcdac8b937434c7ffe8d@172.17.0.8:30303 --network-id=1 --sync-mode=FAST --logging=INFO --genesis-file=/besugenesis.json --graphql-http-enabled --graphql-http-host=0.0.0.0 --host-whitelist=* --rpc-http-enabled --rpc-http-api=ETH,NET,WEB3,ADMIN --rpc-http-host=0.0.0.0`

## Results

Nothing much happens, and after a while, the `sink` says
```

WARNING: An illegal reflective access operation has occurred
--
  | WARNING: Illegal reflective access by com.fasterxml.jackson.databind.util.ClassUtil (file:/opt/besu/lib/jackson-databind-2.10.1.jar) to constructor java.util.OptionalLong()
  | WARNING: Please consider reporting this to the maintainers of com.fasterxml.jackson.databind.util.ClassUtil
  | WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
  | WARNING: All illegal access operations will be denied in a future release

```

In hive right now, both besu and nethermind fails to sync _from_ or _to_ any other client, including themselves. 

Parity, Geth and Aleth can all sync eachother and themselves. I'm not sure how to dig deeper into this.. ?

**Comment by RatanRSur** [comment]
Not sure what's going on with the sink, those warnings are relatively harmless and while they should be dealt with, they're not usually the cause of issues.

In the source logs, it looks like we wait around even though we've found the other node and the test times out. Could you provide the command line invocation required to run these tests? I couldn't find those in the logs.

**Comment by holiman** [comment]
If you're running locally, I'd recommend using this: https://github.com/ethereum/hive/blob/master/test.sh . 
But comment out the other tasks, and only enable this one: https://github.com/ethereum/hive/blob/master/test.sh#L67

**Comment by holiman** [comment]
Should I increase the timeout and run again?

**Comment by RatanRSur** [comment]
Your logs show the client connecting and disconnecting, which is not good and a timeout might not fix that.

I want to look into what caused the disconnects in your case but I'm having trouble getting it to use a local docker build for the tests. I changed the besu dockerfile's `FROM` field to use the docker image I built locally and have been deleting the `hive/clients/besu_latest` image between runs. Is there anything else I need to do?

**Comment by holiman** [comment]
One more thing: you might benefit from using `--docker-nocache .` (where the `.` is a regexp, and thus matches all. You can also do `--docker-nocache besu`). There are two caches, one is the actual host docker, the other is internal to hive, and that one is controlled by `--docker-nocache`

**Comment by holiman** [comment]
However, the `--docker-nocache` cannot evict the base images, so an external `docker pull ... ` is required to update the base images

**Comment by RatanRSur** [comment]
When I use that flag I get:
```
130 ~/go/src/github.com/ethereum/hive besu_bugfind ※ bash test.sh
Running the quick'n'dirty version of the Hive tests, for local development
To the the hive viewer up, you can do

  cd .//hiveviewer && ln -s /tmp/TestResults/ Results && python -m SimpleHTTPServer

And then visit http://localhost:8000/ with your browser.
Log-files and stuff is availalbe in /tmp/TestResults.


mkdir: cannot create directory ‘/tmp/TestResults’: File exists
Tue 05 May 2020 05:17:58 PM EDT Starting hive sync simulation [besu_latest]
./> hive --sim ethereum/sync --client=besu_latest --docker-noshell --docker-nocache --loglevel 4 --results-root /tmp/TestResults  --sim.parallelism 1 --sim.rootcontext --client.checktimelimit=20s
INFO[05-05|17:17:58] docker daemon online                     version=19.03.8-ce
INFO[05-05|17:17:58] building new docker image                client=besu_latest image=hive/clients/besu_latest context=clients/besu dockerfile= branch=latest nocache=false
INFO[05-05|17:18:19] building new docker image                pseudoclient=relay image=hive/pseudoclients/relay context=pseudoclients/relay dockerfile= branch= nocache=false
INFO[05-05|17:18:26] Creating output folder if necessary      folder=workspace/logs
INFO[05-05|17:18:26] creating ethash container
INFO[05-05|17:18:26] building new docker image                image=hive/internal/ethash context=internal/ethash dockerfile= branch= nocache=false
INFO[05-05|17:18:28] generating genesis DAG
INFO[05-05|17:18:28] building simulators for testing          pattern=ethereum/sync
INFO[05-05|17:18:28] building new docker image                simulator=ethereum/sync image=hive/simulators/ethereum/sync context=simulators/ethereum/sync dockerfile= branch= nocache=false
EROR[05-05|17:18:54] failed to build docker image             simulator=ethereum/sync image=hive/simulators/ethereum/sync context=/home/ratan/go/src/github.com/ethereum/hive/simulators/ethereum/sync dockerfile= branch= error="ADD failed: stat /var/lib/docker/tmp/docker-builder245024245/ethereum/sync/sync_test.go: no such file or directory"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8b7b39]

goroutine 1 [running]:
github.com/ethereum/hive/simulators/common.(*TestManager).Terminate(0x0, 0x0, 0x0)
        /home/ratan/go/src/github.com/ethereum/hive/simulators/common/testmanager.go:63 +0x79
main.terminateAndUpdate()
        /home/ratan/go/src/github.com/ethereum/hive/simulator.go:641 +0xd6
main.runSimulations(0x7ffdbb40024e, 0xd, 0xc00025feb8, 0x0, 0x0, 0xc0001918b0, 0xb0ddc0, 0xc0001b2ce0)
        /home/ratan/go/src/github.com/ethereum/hive/simulator.go:39 +0x5f3
main.mainInHost(0xc00025feb8, 0x0, 0x0, 0xc0001918b0, 0x0, 0x2)
        /home/ratan/go/src/github.com/ethereum/hive/hive.go:150 +0x35a
main.main()
        /home/ratan/go/src/github.com/ethereum/hive/hive.go:121 +0x664
```

**Comment by holiman** [comment]
The nil deref is now fixed, but the underlying problem is that it fails to build the simulator container. 
You can try to build it outside of hive, and see if you get any problems. 
The documentation from the `consensus` Dockerfile says how to do it (the quirk is that they both require some files from a common shared folder, so they need to be built from a parent folder, not the same folder where the Dockerfile resides)
```
# To build this in itself, it needs to be built from a parent
# folder, in order to obtain common tools: 
#
# [~/go/src/github.com/ethereum/hive/simulators]
# docker build -f ./ethereum/consensus/Dockerfile  .
```

So try
```
# [~/go/src/github.com/ethereum/hive/simulators]
# docker build -f ./ethereum/sync/Dockerfile  .
```

**Comment by holiman** [comment]
Oh, another thing, it looks like you're on the `besu_bugfind` branch of hive. I created that just to dump some logfiles, but it's a few commits behind master, so you should probably check out `master` instead.

**Comment by RatanRSur** [comment]
Thanks! I switched to master and did what you said but I'm still seeing the same thing:
```
 ~/go/src/github.com/ethereum/hive/simulators master ※ docker build -f ./ethereum/sync/Dockerfile .
Sending build context to Docker daemon  971.3kB
Step 1/13 : FROM golang:1-alpine
 ---> dda4232b2bd5
Step 2/13 : RUN apk add --update git make gcc musl-dev curl jq linux-headers bash
 ---> Using cache
 ---> 8cf8d9ac02b1
Step 3/13 : ENV GO111MODULE=off
 ---> Using cache
 ---> c72a8ab41fd4
Step 4/13 : RUN go get -u -v github.com/derekparker/delve/cmd/dlv
 ---> Using cache
 ---> bed9713681ed
Step 5/13 : ENV GO111MODULE=on
 ---> Using cache
 ---> 158e65dee1e9
Step 6/13 : ADD /ethereum/sync/sync_test.go /go/src/github.com/ethereum/hive/simulators/ethereum/sync/sync_test.go
 ---> Using cache
 ---> 2618ee96db13
Step 7/13 : ADD common /go/src/github.com/ethereum/hive/simulators/common
 ---> Using cache
 ---> e4951cf8d7c4
Step 8/13 : ADD /ethereum/sync/simplechain /simplechain
 ---> Using cache
 ---> 0b429ffe129a
Step 9/13 : RUN (cd /go/src/github.com/ethereum/hive/simulators/ && go mod init)
 ---> Using cache
 ---> bc70c055a32b
Step 10/13 : ADD /ethereum/sync/tests.sh /tests.sh
 ---> Using cache
 ---> cfeffb000125
Step 11/13 : RUN chmod +x /tests.sh
 ---> Using cache
 ---> 63f9d18fa721
Step 12/13 : EXPOSE 2345 8545 8546 8080 30303 30303/udp
 ---> Using cache
 ---> 8cddc2d9a539
Step 13/13 : ENTRYPOINT ["/tests.sh"]
 ---> Using cache
 ---> fb31fc78462a
Successfully built fb31fc78462a
```
```
 ~/go/src/github.com/ethereum/hive master ※ notify bash test.sh
Running the quick'n'dirty version of the Hive tests, for local development
To the the hive viewer up, you can do

  cd .//hiveviewer && ln -s /tmp/TestResults/ Results && python -m SimpleHTTPServer

And then visit http://localhost:8000/ with your browser.
Log-files and stuff is availalbe in /tmp/TestResults.


mkdir: cannot create directory ‘/tmp/TestResults’: File exists
Wed 06 May 2020 11:04:39 AM EDT Starting hive sync simulation [besu_latest]
./> hive --sim ethereum/sync --client=besu_latest --docker-noshell --docker-nocache --loglevel 4 --results-root /tmp/TestResults  --sim.parallelism 1 --sim.rootcontext --client.checktimelimit=20s
INFO[05-06|11:04:39] docker daemon online                     version=19.03.8-ce
INFO[05-06|11:04:39] building new docker image                client=besu_latest image=hive/clients/besu_latest context=clients/besu dockerfile= branch=latest nocache=false
INFO[05-06|11:04:39] building new docker image                pseudoclient=relay image=hive/pseudoclients/relay context=pseudoclients/relay dockerfile= branch= nocache=false
INFO[05-06|11:04:39] Creating output folder if necessary      folder=workspace/logs
INFO[05-06|11:04:39] creating ethash container
INFO[05-06|11:04:39] building new docker image                image=hive/internal/ethash context=internal/ethash dockerfile= branch= nocache=false
INFO[05-06|11:04:39] generating genesis DAG
INFO[05-06|11:04:40] building simulators for testing          pattern=ethereum/sync
INFO[05-06|11:04:40] building new docker image                simulator=ethereum/sync image=hive/simulators/ethereum/sync context=simulators/ethereum/sync dockerfile= branch= nocache=false
EROR[05-06|11:04:40] failed to build docker image             simulator=ethereum/sync image=hive/simulators/ethereum/sync context=/home/ratan/go/src/github.com/ethereum/hive/simulators/ethereum/sync dockerfile= branch= error="ADD failed: stat /var/lib/docker/tmp/docker-builder394494411/ethereum/sync/sync_test.go: no such file or directory"
CRIT[05-06|11:04:40] failed to run simulations                error="simulators/ethereum/sync: ADD failed: stat /var/lib/docker/tmp/docker-builder394494411/ethereum/sync/sync_test.go: no such file or directory"
```
`test.sh`:
```
#!/bin/bash

#
# This is a little test-script, that can be used for a some trial runs of clients.
#
# This script runs all production-ready tests, but does so with very restrictive options,
# and should thus complete in tens of minutes
#

HIVEHOME="./"

# Store results in temp
RESULTS="/tmp/TestResults"

#FLAGS="--docker-noshell --docker-nocache ."
FLAGS="--docker-noshell --docker-nocache --loglevel 4"
FLAGS="$FLAGS --results-root $RESULTS "
FLAGS="$FLAGS --sim.parallelism 1 --sim.rootcontext --client.checktimelimit=20s"

echo "Running the quick'n'dirty version of the Hive tests, for local development"
echo "To the the hive viewer up, you can do"
echo ""
echo "  cd $HIVEHOME/hiveviewer && ln -s /tmp/TestResults/ Results && python -m SimpleHTTPServer"
echo ""
echo "And then visit http://localhost:8000/ with your browser. "
echo "Log-files and stuff is availalbe in $RESULTS."
echo ""
echo ""


function run {
  echo "$HIVEHOME> $1"
  (cd $HIVEHOME && $HIVEHOME$1)
}

function testconsensus {
  client=$1
  echo "$(date) Starting hive consensus simulation [$client]"
  run "hive --sim ethereum/consensus --client $client --sim.loglevel 6 --sim.testlimit 2 $FLAGS"
}
function testgraphql {
  echo "$(date) Starting graphql simulation [$1]"
  run "hive --sim ethereum/graphql --client $1 $FLAGS"
}

function testsync {
  echo "$(date) Starting hive sync simulation [$1]"
  run "hive --sim ethereum/sync --client=$1 $FLAGS"
}

function testdevp2p {
  echo "$(date) Starting p2p simulation [$1]"
  run "hive --sim devp2p --client $1 $FLAGS"
}

mkdir $RESULTS

# Sync are quick tests
#

# These three can succsessfully sync with themselves
#testsync parity_latest
#testsync go-ethereum_latest
#testsync aleth_nightly,parity_latest,go-ethereum_latest

# These two are failing - even against themselves
testsync besu_latest       # fails
#testsync nethermind_latest # fails

#testsync besu_latest,nethermind_latest

#testsync go-ethereum_latest go-ethereum_stable
#testsync go-ethereum_latest parity_latest
#testsync go-ethereum_latest aleth_nightly
#testsync go-ethereum_latest nethermind_latest
#testsync go-ethereum_latest besu_latest

# GraphQL implemented only in besu and geth
#

#testgraphql go-ethereum_latest
#testgraphql besu_latest


# The devp2p tests are pretty quick -- a few minutes
#testdevp2p go-ethereum_latest
#testdevp2p nethermind_latest
#testdevp2p besu_latest
#testdevp2p parity_latest


# These take an extremely long time to run
#testconsensus aleth_nightly
#testconsensus go-ethereum_latest
#testconsensus parity_latest
#testconsensus nethermind_latest
#testconsensus besu_latest



```

**Comment by holiman** [comment]
Interesting. So you can build it outside of hive, but it fails when building from hive.  What OS are you using?

**Comment by holiman** [comment]
One thing you can try, is to omit `--docker-noshell`. Docker-noshell means that hive will use the actual docker on your machine, otherwise there will be an additional docker-in-docker level. So
```
./> hive --sim ethereum/sync --client=besu_latest  --docker-nocache . --loglevel 4 --results-root /tmp/TestResults  --sim.parallelism 1 --sim.rootcontext --client.checktimelimit=20s
```
Also, looks like you added `--docker-nocache` but forgot to specify a regexp

**Comment by holiman** [comment]
Ps: did you get it to work ? And if so, what was the problem?

**Comment by RatanRSur** [comment]
Yup! Works locally with the branch on ethereum/hive#287

**Comment by RatanRSur** [comment]
I'll close this for now but feel free to reopen if you see it still.

**Comment by RatanRSur** [comment]
I was missing the regex like you said but ultimately it still didn't pick up the local docker image so I wouldn't have been able to fix it if it was a besu issue. Luckily it was just config flags so it could be done on the hive side.

**Comment by holiman** [comment]
> didn't pick up the local docker 

No, it wouldn't have. You'd have had to push it to docker hub, then add a new client "ratansur/besu" or something that, I think. Thanks for fixing!

**Comment by RatanRSur** [comment]
Of course! Thanks for your responsiveness and helpfulness. It was great that I could rely on you who knows the system better instead of ramping myself up on it.
