### ISSUE TITLE
Strange behavior for MiningOptionsTest

### ISSUE THREAD

**Issue by gabrieledm** [hyperledger/besu#8999]
If I run all the tests under the `app` folder only one test fails: `extraDataDefaultValueIsBesuVersion` into `org.hyperledger.besu.cli.options.MiningOptionsTest`.

But if I run the test `extraDataDefaultValueIsBesuVersion` alone or all the tests in `org.hyperledger.besu.cli.options.MiningOptionsTest`, the test passes.

**Comment by macfarla** [comment]
@gabrieledm are you still getting this on latest main? I can't reproduce

**Comment by gabrieledm** [comment]
Hi @macfarla, sorry for my late response.

Yes, I'm using the latest main.

Attached there are two videos showing the tests I'm running.

- [All_in_besu.app.test](https://github.com/user-attachments/assets/b5129fc4-6de2-488e-a06e-9cfcc64ffa70)
- [MiningOptionsTest](https://github.com/user-attachments/assets/ad7c5e42-5eb7-49c7-87cb-2e5c71193698)

The only difference I can spot it that the tests for `MiningOptionsTest` are running as a `gradle` configuration.
Instead, the tests for `All_in_besu.app.test` are running as `JUnit` configuration.

**Comment by macfarla** [comment]
@gabrieledm is this issue resolved by #9342 ?

**Comment by gabrieledm** [comment]
> [@gabrieledm](https://github.com/gabrieledm) is this issue resolved by [#9342](https://github.com/hyperledger/besu/pull/9342) ?

I'll check and give feedback ASAP.

**Comment by gabrieledm** [comment]
The strange behavior still happens but I analyzed it in more detail.

Basically, when the tests are executed using `gradle` a JAR is build metadata are correctly populated and so the variable `VERSION` on line `74` in file `org.hyperledger.besu.util.BesuVersionUtils` is correctly populated with the actual version of Besu.

When the tests are executed using directly JUnit this not happens because probably the JAR is not build before running the tests and the `VERSION` on line `74` in file `org.hyperledger.besu.util.BesuVersionUtils` is populated with `null`.

Hope this help

**Comment by macfarla** [comment]
@gabrieledm I can't reproduce this on my local machine so I'm going to unassign myself. Feel free to propose a solution if you have ideas

**Comment by gabrieledm** [comment]
Hi @macfarla, I found the reason behind this strange behavior.

Basically when the tests are executed using directly `JUnit` (without the build phase in `gradle`) the JAR is not generated and the following line in the file `org.hyperledger.besu.util.BesuVersionUtils` throws an Exception.

```
JarURLConnection jarConnection = (JarURLConnection) url.openConnection();
```

This cause that the `implVersion` variable and, consequently, the `VERSION` variable remains `null`.

Thus the `org.hyperledger.besu.cli.options.MiningOptionsTest.extraDataDefaultValueIsBesuVersion` test fails.


I can propose two solutions

- Change the regex in the test to match also the case `besu null`
- Add a piece of code in the catch block in `org.hyperledger.besu.util.BesuVersionUtils` to populate the `implVersion` variable with something like `junit-tests` and update the regex to match also this case.

Waiting for your feedback about which approach you prefer.

After I'll open a PR.

**Comment by macfarla** [comment]
@gabrieledm I think I prefer the second option -
Add a piece of code in the catch block in org.hyperledger.besu.util.BesuVersionUtils to populate the implVersion variable with something like junit-tests and update the regex to match also this case.

**Comment by gabrieledm** [comment]
Ok, thanks for the feedback.

I'll open a PR for this.

**Comment by gabrieledm** [comment]
Hey @macfarla, I opened the PR #9422

**Comment by macfarla** [comment]
fixed by #9422
